---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  ansible_verbose: false
  ansible_verbosity: 2


platforms:
  #- name: ubuntu/trusty64
  - name: ubuntu-18.04
  - name: centos-7

suites:
  - name: default
