---
driver:
  name: docker
  privileged: true

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  ansible_verbose: true 
  ansible_verbosity: 2
  requirements_path: dependencies.yml

platforms:
  #- name: ubuntu/trusty64
  - name: ubuntu-18.04

suites:
  - name: default
