- name: Ensure group "devopsmeetup" exists
  group:
    name: devopsmeetup
    state: present


- name: Add the user 'johnd' with a specific uid and a primary group of 'admin'
  user:
    name: dev
    comment: Dev Ansible
    group: devopsmeetup